- name: ansible test playbook
  connection: network_cli
  gather_facts: false
  hosts: all
  tasks:

          - name: Get config for VyOS devices
            vyos_facts:
                    gather_subset: all

          - name: show list of the config
            debug:
                    msg: "The hostname is {{ ansible_net_hostname }} and the OS is {{ ansible_net_version }}"

